# Generated by Django 4.2.13 on 2024-06-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Form',
            fields=[
                ('Attendance_Form_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Moment', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Latitude', models.DecimalField(decimal_places=15, default=0, max_digits=19)),
                ('Longitude', models.DecimalField(decimal_places=15, default=0, max_digits=19)),
                ('Radius', models.IntegerField(default=0)),
                ('Time_Create', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Class_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('Lecturer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Lecturer', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Student', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject_Name', models.CharField(max_length=100)),
                ('Class_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class')),
                ('Lecturer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='Students',
            field=models.ManyToManyField(through='attendance.SubjectEnrollment', to='attendance.student'),
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('Face_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Face_Name', models.CharField(max_length=100)),
                ('Face_Img', models.ImageField(upload_to='faces/')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Mark',
            fields=[
                ('Attendance_Mark_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Status_Attendance', models.BooleanField()),
                ('Time_Late', models.BooleanField()),
                ('Time_Attendance', models.DateTimeField(auto_now_add=True)),
                ('Attendance_Form_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance_form')),
                ('Face_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.face')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance_form',
            name='Subject_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Account_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Lecturer_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.lecturer')),
                ('Student_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.student')),
            ],
        ),
    ]
